### ISSUE TITLE
Few QR Code is not able to read by this library

### ISSUE THREAD

**Issue by pradeepngupta** [mebjas/html5-qrcode#101]
I was dealing with QR Code generation on Arduino with Richard Moore QRCode library and printing on TFT LCD (Adafruit ST7735 ) device.
I used this library in my webpage and when reading that QR code, But this library is not able to read the QR code.
Then I used the library https://github.com/schmich/instascan, and to my good luck this is able to read the QR code.

I have taken a look deeply in both the library, the underlying library for qr scanner is same except the below differences:
1) This library is using the LazarSoft jsqr library which is a port of ZXing qrcode scanner.
2) Instascan is using Emscripten JavaScript build of the C++ port of the ZXing Java library.

Could you please take a look whiat is the difference between two scanners and what lacking in this scanner?

Please let me know if you need any other information.

Thanks,
Pradeep Gupta

**Comment by max2ti** [comment]
Can you share a photo of a QR you can't read?

**Comment by pradeepngupta** [comment]
I don't have photo. I am directly doing the QR Scan of the QR printed on the device using Arduino QR code library by Richard Moore.
I tried taking the photo from my camera, but not sure whether this image can be readable by any QR scanner as i feel it is coming blurred.
Please check and let me know.
![IMG_20200729_093114__01](https://user-images.githubusercontent.com/6321439/90558906-70bfb500-e1ba-11ea-8afb-e7a02fd0976a.jpg)
![IMG_20200729_093114__01__01](https://user-images.githubusercontent.com/6321439/90558921-74533c00-e1ba-11ea-99b6-c90fb41f5e69.jpg)

**Comment by max2ti** [comment]
I can't read it with any library but it's probably because of the quality of the photo. Anyway I think your problem is that your QR is bright on a dark background (standard is black on white) and this library doesn't support it (yet?) according to this other issue https://github.com/mebjas/html5-qrcode/issues/94

I don't know how hard it would be for you to do it but if you can try reversing the colors.

**Comment by mebjas** [comment]
@pradeepngupta 
Thanks for raising the request - this gives a valid use case for issue #94 as @max2ti pointed out.

Would it be possible to share a clearer picture so I can prototype inversion logic - if it works fine, happy to add it as a supported configuration.

**Comment by pradeepngupta** [comment]
Thanks @mebjas 
@max2ti Sorry for the delay, I changed the inverted background. attached is the latest image.
Even then I can't able to read the QR code with this library from my mobile phone (QR code displaying on TFT LCD).

The only library which can able to read this QR code is https://github.com/schmich/instascan
During these 10 days, I was able to merge the current library (for look n feel) with the instascan (for scanner).

Please see what is the difference between html5-qrcode and instascan libraries from the scanner point of view.
I see the only difference is:
html5-qrcode is using jsqrcode which is a port of ZXing qrcode scanner.
And instacan is using  Emscripten JavaScript build of the C++ port of the ZXing Java library.

**Comment by pradeepngupta** [comment]
![IMG-20200821-WA0073 (2)](https://user-images.githubusercontent.com/6321439/91613068-6f517200-e99c-11ea-9859-d8a6e5cd8094.jpg)

Please see the latest image of the QR code i am trying to read.

**Comment by mebjas** [comment]
@pradeepngupta - Thanks for inverting the image and sharing with us. I tried the scanner running on Pixel 3a (Google Chrome) and Iphone 7 (Safar) and both of them were able to scan this:

| Pixel 3a, Google Chrome | Iphone 7, Safari |
| ------- | ------- |
|<img src="https://user-images.githubusercontent.com/3007365/91631789-ea537080-ea0e-11ea-9f33-0f1a9e8a863f.png" width="250">| <img src="https://user-images.githubusercontent.com/3007365/91632040-b11c0000-ea10-11ea-9f97-538bd6e3ec63.png" width="250">|

> The only library which can able to read this QR code is https://github.com/schmich/instascan
> During these 10 days, I was able to merge the current library (for look n feel) with the instascan (for scanner).
>
> Please see what is the difference between html5-qrcode and instascan libraries from the scanner point of view.
I see the only difference is:
> html5-qrcode is using jsqrcode which is a port of ZXing qrcode scanner.
> And instacan is using Emscripten JavaScript build of the C++ port of the ZXing Java library.

Thanks for investigating and sharing, I'll definitely try out the underlying scanner in instascan and if it turns out to be working better for most scenarios happy to migrate. There have been bunch of issues on wrong scans by the scanner.

Also, I am interested in trying out #94 as a experimental change to see if it can meet the usecase without you having to invert the QR code on the embedded display.

**BTW cool work, can you share more on what you are trying to do in this project?**

**Comment by mebjas** [comment]
Can you share some more inverted QR codes like you had before (blue background and white code) so I can test out the inversion logic.

**Comment by pradeepngupta** [comment]
@mebjas Thanks for the update here. I am not be having more inverted qr code as i have already migrated to use standard QR (White background with black QR). And this is more standard and good look as well.

Its good that you are able to scan with Google Pixel3 and Iphone 7. What I have tried till now are various lower models like iPhone 6 / One Plus / Real Me 1/ Moto G / Moto X / IPAD Air 2. But all these devices were unable to read this QR code.
Might be some latest mobile phone is able to read using the html5-qrcode library which might not be supported by lower model mobile phone.
When you are saying 'There have been bunch of issues on wrong scans by the scanner.' what do you mean by this? Do you meant wrong scan done by this library or instascan library.

On these two library differences:

Please see what is the difference between html5-qrcode and instascan libraries from the scanner point of view.
I see the only difference is:
html5-qrcode is using jsqrcode which is a port of ZXing qrcode scanner. (Last commit on LazarSoft jsQRCode is Apr 18 2017)
And instascan is using Emscripten JavaScript build of the C++ port of the ZXing Java library. (Last commit on instascan is Apr 30 2017, but the port of zxing library might have taken much before, might be Nov 22, 2016)

I believe that might be a difference why using instascan, these lower model devices are working good.

**Comment by mebjas** [comment]
Update: Library has been migrated to use `Zxing-js` instead of `Lazarsoft` - https://github.com/mebjas/html5-qrcode/blob/master/changelog.md#version-200

**Comment by mebjas** [comment]
Closing this issue for now, please reopen if this still exists.

**Comment by tuzunerc** [comment]
This is not because the view is blurred it's because the QR code is white... Invert it (should be white background and black qr code) it'll most probably read...
