### ISSUE TITLE
Compatibility - [Android 11] [Chrome 88.0 ] - [Call stopScan will cause crash]

### ISSUE THREAD

**Issue by bastienWang** [mebjas/html5-qrcode#159]
**Describe the bug**
I use my phone link to Demo site, I repeated the start scanning and stop scanning, browser will cause crash. 

**Describe the browser:**
 - OS: [Android 11]
 - Browser [Chrome]
 - Version [88.0]

**Additional context**
If use Chrome 83.0 is OK.

**Comment by MrGussio** [comment]
@bastienWang As you might see in the activity feed of this issue, I have found a solution to this issue. If you just use the compiled JS files, they can be found already in the [pull request](https://github.com/mebjas/html5-qrcode/pull/169) contents.

**Comment by jdtimmerman** [comment]
This issue is still present and I can confirm that @MrGussio´s change (which i rebased onto the current master) solves this issue for me (on Chrome 89). @mebjas could you please triage this? I´d say it´s an high-prio issue.

I did notice one of the tests are failing, but I also had some issues with the transpiling so this could just be an issue on my environment.

**Comment by MrGussio** [comment]
@jdtimmerman I had some transpiling issues too - IIRC I eventually managed to do it by hand using Babel. Good to know that the fix also works for the most recent master version.

**Comment by mebjas** [comment]
Thanks for reporting the issue and thanks @MrGussio for the fix & @jdtimmerman for the verification.

Added a comment to the PR, happy to merge asap. (Sorry have been a busy lately).

**Comment by mebjas** [comment]
Thanks for the fix @MrGussio - it has been merged and published.

 - https://github.com/mebjas/html5-qrcode/releases/tag/V2.0.2
 - https://www.npmjs.com/package/html5-qrcode/v/2.0.2

Closing this issue now.
