### ISSUE TITLE
Scanning without ID doesn't actually scan

### ISSUE THREAD

**Issue by Damsjov** [mebjas/html5-qrcode#220]
Hi

I implemented this code:

```js
const html5QrCode = new Html5Qrcode("reader");
const qrCodeSuccessCallback = message => {
    document.getElementById("qr-reader-results").innerHTML = `<div>`+message+`</div>`; 
}
const config = { fps: 10, qrbox: 250 };
html5QrCode.start({ facingMode: "environment" }, config, qrCodeSuccessCallback);
html5QrCode.stop().then(ignore => {
}).catch(err => {
});
```

And sure enough it opened the back camera alright. But it never actually scans anything - it just sits there...

What am I missing?

Thanks, Claus

**Comment by mebjas** [comment]
Can you omit the `stop()` code?

Try with just the following?

```js
const html5QrCode = new Html5Qrcode("reader");
const qrCodeSuccessCallback = message => {
    document.getElementById("qr-reader-results").innerHTML = `<div>`+message+`</div>`; 
}
const config = { fps: 10, qrbox: 250 };
html5QrCode.start({ facingMode: "environment" }, config, qrCodeSuccessCallback);
```

**Comment by Damsjov** [comment]
Thanks, but it still doesn't 'fire' - it just 'looks'...

**Comment by mebjas** [comment]
- Can you maybe add a video to show what is happening?
 - Do you see something on console?
-  Does the demo page work for you? https://blog.minhazav.dev/research/html5-qrcode
- What browser, OS are you using?

**Comment by Damsjov** [comment]
Hi,

Well, a video would just show the camera on and nothing happening. There is nothing in the console - it looks like an event that is never fired - or whatever it is called. 

This code works: 

function onScanSuccess(qrCodeMessage) {
                document.getElementById("qr-reader-results").innerHTML = "[something]";
                document.getElementById('reader').style.display = 'none';
                // Optional: To close the QR code scannign after the result is found
                html5QrcodeScanner.clear();
            }

            function onScanError(errorMessage) {
                // handle on error condition, with error message
                resultContainer.innerHTML += `<div>${errorMessage}</div>`;
            }

            var html5QrcodeScanner = new Html5QrcodeScanner(
                "reader", { fps: 10, qrbox: 250 });

            html5QrcodeScanner.render(onScanSuccess);

I have tryed it on Windows using Edge and Android using Chrome. Same result.

Thanks,
Claus

**Comment by marco-torretta** [comment]
Hi,

I have the same issue. The scanner opens correctly with the back camera, but it doesn't scan anything.
Tested on iOS 14.7 on iPhone 11 Pro.

This issue happens only if the `new Html5Qrcode` method without camera ID is used.
Using the `new Html5QrcodeScanner` works but it does not allow to preselect the back camera.

I find this issue pretty important because:
1) since no one uses the selfie camera to scan QR codes, the only way to automatically preselect  the back camera is to use the `new Html5Qrcode` method without camera ID, which seems to not work properly.
2) using the `new Html5QrcodeScanner` works fine but requires the user to select which camera to use, which is a bad UX in the majority of cases and a waste of time.

The solutions could be to fix the issue on the `new Html5Qrcode` method, or to allow developers to force the back camera as default also on the `new Html5QrcodeScanner` method, which is missing right now.

**Comment by Topya123** [comment]
> Can you omit the `stop()` code?
> 
> Try with just the following?
> 
> ```js
> const html5QrCode = new Html5Qrcode("reader");
> const qrCodeSuccessCallback = message => {
>     document.getElementById("qr-reader-results").innerHTML = `<div>`+message+`</div>`; 
> }
> const config = { fps: 10, qrbox: 250 };
> html5QrCode.start({ facingMode: "environment" }, config, qrCodeSuccessCallback);
> ```

This code works for me. But how to stop camera?

**Comment by mebjas** [comment]
@Jonnas123 When do you want to stop the camera?

@marco-torretta  please share sample code or a codepen link I can debug? (ditto for @Damsjov)
