### ISSUE TITLE
how to change Backend camera on android 

### ISSUE THREAD

**Issue by ChandraOrbit** [mebjas/html5-qrcode#3]
how to change the display to the rear camera on the smartphone ?

**Comment by mhatvan** [comment]
Hey ChandraOrbit, at my company, we found a solution to use all cameras available.
Since this library is more than 3 years old, MediaStreamTrack seems to be deprecated.

you will need to fork the html5-qrcode.js file yourself, switch out the part with MediaStreamTrack.getSources(gotSources) with the example in this one -> 
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices
and also filter for device.kind === 'videoinput', so you dont get the audioinputs

then you should be all set and it works ;)

**Comment by ChandraOrbit** [comment]
OK thanks, I am now trying the latest update update from matthiaseigner

**Comment by mebjas** [comment]
Added more support in the demo: https://blog.minhazav.dev/research/html5-qrcode.html
