### ISSUE TITLE
Question: Does pushing fps above 30 actually make a difference?

### ISSUE THREAD

**Issue by oivvio** [mebjas/html5-qrcode#440]
I'm experimenting with fps (frames per seconds) settings. The iPhone 8 (the oldest device I'm testing on) seems to handle 200 fps without problems. Battery consumption doubles but is still manageable.  My question is this: Given that the video feed is probably not more than 30 fps on most devices, does pushing the scanning frequency above 30 fps actually help in reading codes faster?

**Comment by emkowale** [comment]
I would be curious to know the answer to this as well. I can confirm the battery draining on this higher fps.

**Comment by ROBERT-MCDOWELL** [comment]
that does not make sense to go higher than 10 fps since each frame is analyzed by JS and so the CPU, draining indeed the battery

**Comment by mebjas** [comment]
Probably not. Even higher than 10 might not be useful. IIRC the human reaction time is often 100-200 ms so even 5fps might do fine.

Note that, even if you set fps to 200, the library IIRC does one scan after the other. So it will not issue 200 takes in a second instead finish one full scan, wait for 1/200 s and trigger the next scan. Due to realistic latency constraints there might be an upper limit on max fps observed per device.

**Comment by mebjas** [comment]
(More suitable for discussion than issue)
