### ISSUE TITLE
The camera won't launch.

### ISSUE THREAD

**Issue by potatodyn** [mebjas/html5-qrcode#680]
**Describe the bug**
After I allowed the site to access my camera it got stuck on launching the camera, but it won't launch, I've waited for almost an hour.

**Expected behavior**
I expected that after I allowed the camera to be used I'll proceed to choose what camera I want to use and the rest is history.

**Screenshots**
![image](https://user-images.githubusercontent.com/109524078/213742079-85254a96-8881-4449-acf0-b825693836e8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX, Chrome
 - Version: Version 94.0.4606.69, Version 109.0.5414.75

**Comment by 22001797** [comment]
Nu pot permite accesul camerei in booster

**Comment by Erenyeager31** [comment]
I am facing exactly the same issue.Whenever I allow the permission for camera it gets stuck on 'launching camera'.I tried looking for the solution on many websites but couldn't find one.

**Comment by Erenyeager31** [comment]
Hey there ! I found a solution for this last night

If you are using vscode you need to download this extension called 'live server'.
![liverserver](https://user-images.githubusercontent.com/109287426/215311126-f934f126-da42-416e-a13a-26e2de3d9dfb.jpg)

Once downloaded you need to click on 'Go live' at the right bottom of the screen as shown in image
![golive](https://user-images.githubusercontent.com/109287426/215311123-463dd9a9-9ea3-4caa-9e78-f31ed2d58fc9.jpg)

The problem is when you run the website simply through your files and folders it is unable to open the camera.
But when you launch it through local server on your computer it works

**Comment by mebjas** [comment]
Camera access doens't work without `https://` or without `localhost`.

Opening a file directly doesn't work.
