### ISSUE TITLE
Allow setting video constraints

### ISSUE THREAD

**Issue by max2ti** [mebjas/html5-qrcode#97]
**Is your feature request related to a problem? Please describe.**
To improve performances I would like to change the resolution of the video stream.

**Describe the solution you'd like**
To do it I need to be able to set the constraints for the `getUserMedia` call. A good place to do it might be inside the `configuration` parameter of the `start` call. 

Then it could be used like:
```javascript
let videoConstraints = {
    deviceId: { exact: cameraId }
};
if (configuration.videoConstraints) {
    videoConstraints = {
        ...videoConstraints,
        ...configuration.videoConstraints
    }; 
}
```

By setting the video constraints directly, the `cameraId` parameter becomes redundant, but for both back-compatibility and simpler use-case when the user doesn't care about anything but the camera, it could left it there.

**Comment by mebjas** [comment]
Are there specific constraints that you'd like to control? 

Since the library abstracts the underlying APIs, I feel flat set of non conflicting & documented configuration at the library level would be more helpful to users, rather than having to lookup HTML Api documentations. While I understand this brings more power to the consumers.

**Comment by max2ti** [comment]
Let's see, these are the constraints chrome desktop supports, I'll mark those that I think might be useful:

```
--> aspectRatio: true
autoGainControl: true
brightness: true
channelCount: true
colorTemperature: true
contrast: true
--> deviceId: true
echoCancellation: true
exposureCompensation: true
exposureMode: true
exposureTime: true
--> facingMode: true
focusDistance: true
focusMode: true
--> frameRate: true
groupId: true
--> height: true
iso: true
latency: true
noiseSuppression: true
pointsOfInterest: true
resizeMode: true
sampleRate: true
sampleSize: true
saturation: true
sharpness: true
torch: true
whiteBalanceMode: true
--> width: true
zoom: true
```

The reason why I think exposing (optionally) the HTML api is good is that for each of these you can refine the constraints by using the `min`, `max`, `ideal`, `exact` keywords (https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia). 90+% of users will likely just need `facingMode` but the rest who need more control might want any combination of any other constraint (including the possibility to use `min`, `max`, `ideal`, `exact` for each). Those "power users" probably already know how the underlying api works and being able to use them directly might be both the easiest and best solution for them, rather than having to learn the way the library wrapped them.

I understand and agree that mixing native constraint with wrapped ones might be confusing, maybe the best thing would be making it so that you can either use the limited but easy wrapped constraints or the HTML api. I don't know, I'm just thinking aloud.

Being able to control the resolution and frame rate of the stream allows for better performance tuning, in whatever way it's implemented I think it would be a plus for the library.

**Comment by mebjas** [comment]
Thanks for the detailed explanation. 

_The general problem with exposing "more" for the 10% use-case is as you mentioned it can confuse the 90% users and lead to issues manifesting in different forms probably due to incorrect usage. This is in general issues with adding more knobs to tune and for some reason the library is already heading in that direction._

And the whole purpose I started writing this was to hide the details of how to handle html5's MediaDevices, local streams, video constraints etc from users.

**That said** - this is still a valid ask and for starters one thing I could do is to support this requirement in a hidden way (no documentation, but the library would honour it if provided). 

Once we have either:
 - more users requesting the same support.
 - enough confidence on how the constraints are honoured by different browsers / environment.

Expose it in louder way or just pick the important ones (some of those you pointed out as well as other that start to look important later).

As a quick design decision I think it'd be fair to prioritise `videoConstraints` over the other configurations passed in case there is conflict
```js
let config = {
    // .. generally supported configs below
    fps: 10,
    qrbox: 250,
    aspectRatio: 1.333,
    // .. let's say in beta configs below
    videoConstraints: {
        aspectRatio: 1.77778      // <-- this would be honoured 
    }
};
let html5QrcodeScanner = new Html5QrcodeScanner(
	"reader",  config, /* verbose= */ true);
html5QrcodeScanner.render(onScanSuccess, onScanFailure);
```

**Comment by max2ti** [comment]
Looks good to me!

**Comment by mebjas** [comment]
Created a PR to support passing `videoConstraints`. Along with this I added two new **experimental** APIs to `Html5Qrcode` that will

 - `getRunningTrackCapabilities()`: get capabilities of running track
 - `applyVideoConstraints(videoConstaints)`: Apply a few supported constraints to running track

A WIP demo: https://blog.minhazav.dev/research/html5qrcode-video-constraints

I observed Android/Chrome to extend support for various capabilities but I could only see `frameRate` to be functional.

PTAL at the PR if you get a chance and PLMK what you think.

**Comment by mebjas** [comment]
Please reopen this issue, if something is still missing

**Comment by e-magon** [comment]
Hi
I'm having issues setting the aspect ratio of the camera on Firefox, macOS.
Brave Browser (Chromium) on macOS is fine, the aspect ratio is correct when it's set in the `config` object or the `videoConstraints` one.

In Firefox, instead, it uses the default webcam aspect ratio. I also noticed that even the `frameRate` option in the `videoConstraints` isn't applied in Firefox.

I don't know if this is the right place to talk about this issue or if I should open a new issue, and I don't know if this problem is caused by Firefox (or macOS) or this library.
Let me know if you want me to open a new issue.

Thank you
